"""P2-B Army no-drift guard (Codex iter-2 #2).

Captures a deterministic golden of `parse_glossary_entries(ARMY, ...)` output
on the committed real-PDF parser fixtures, BEFORE the DoD `inline_split` change
to glossary.py, and asserts byte-identical output AFTER. This proves the
additive `term_gate_mode=="inline_split"` branch does not alter Army's
`"spatial"` parse path (counts alone — the prior bar — would miss reordering,
metadata, confidence, or flag drift).

Golden is generated by running this module with REGEN=1 on un-edited code:
    REGEN=1 ./.venv/bin/python -m pytest tests/test_army_no_drift.py -q
which writes tests/fixtures/army_no_drift/<name>.golden.json and is committed
as the pre-edit baseline.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from fedresearch_dictionary_extractor.extractors.glossary import parse_glossary_entries
from fedresearch_dictionary_extractor.profiles import get_profile

PARSER_FIXTURE_DIR = Path(__file__).parent / "fixtures" / "glossary_parser_v0.5"
GOLDEN_DIR = Path(__file__).parent / "fixtures" / "army_no_drift"
ARMY = get_profile("army")


def _make_mock_doc(fixture: dict) -> MagicMock:
    """Reconstruct a fitz-Document-like object from a captured parser fixture.

    Mirrors the harness in test_glossary_parser_fixtures.py so the Army golden
    is produced by the exact same code path the existing suite exercises.
    """
    total = fixture["total_pages"]
    page_data: dict[int, dict] = {int(k): v for k, v in fixture["pages"].items()}

    page_mocks = []
    for i in range(total):
        page = MagicMock()
        if i in page_data:
            page.get_text.side_effect = lambda fmt="text", _i=i: (
                page_data[_i]["page_dict"] if fmt == "dict" else page_data[_i]["page_text"]
            )
        else:
            page.get_text.side_effect = lambda fmt="text": (
                {"blocks": []} if fmt == "dict" else ""
            )
        page.rect = MagicMock()
        page.rect.height = 792
        page.get_label = MagicMock(return_value=None)
        page_mocks.append(page)
    doc = MagicMock()
    doc.__getitem__.side_effect = lambda i: page_mocks[i]
    doc.__len__.return_value = total
    return doc


def _run(fixture: dict) -> list[dict]:
    doc = _make_mock_doc(fixture)
    start, end = fixture["capture_range_0idx"]
    return parse_glossary_entries(doc, start, end, ARMY)


FIXTURES = sorted(PARSER_FIXTURE_DIR.glob("*.json"))


@pytest.mark.parametrize("fx_path", FIXTURES, ids=lambda p: p.stem)
def test_army_parse_no_drift(fx_path: Path) -> None:
    fixture = json.loads(fx_path.read_text())
    result = _run(fixture)
    golden_path = GOLDEN_DIR / f"{fx_path.stem}.golden.json"

    if os.environ.get("REGEN") == "1":
        GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
        golden_path.write_text(json.dumps(result, indent=1, sort_keys=True, default=str) + "\n")
        pytest.skip(f"REGEN: wrote {golden_path.name}")

    assert golden_path.exists(), f"missing golden {golden_path}; run REGEN=1 on clean code"
    expected = json.loads(golden_path.read_text())
    got = json.loads(json.dumps(result, sort_keys=True, default=str))
    assert got == expected, f"Army parse drifted for {fx_path.stem}"
